name: Deploy Website to VPS

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Copy files to VPS using SSH key
      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."              # Everything in the repo
          target: "/var/www/html"  # Destination on VPS
          port: 22                 # Default SSH port
          strip_components: 0      # Keep folder structure as is
          overwrite: true          # Overwrite files if already exist

      # 3️⃣ Optional: Restart Nginx (or any service)
      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
